services:
  db:
    image: mysql:8.0
    container_name: shop-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: loja_virtual
      MYSQL_ROOT_PASSWORD: root_password_here
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: ./alaroko-store
      dockerfile: Dockerfile.override
    container_name: nextjs-app
    restart: on-failure
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:root_password_here@db:3306/loja_virtual?connection_limit=20&pool_timeout=30
      NODE_ENV: development
      DATABASE_HOST: "db"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "user_password_here"
      DATABASE_NAME: "loja_virtual"
    volumes:
      # - ./alaroko-store/generated:/app/generated # @isabellydemelolima48-sudo needs this
      # - ./alaroko-store/prisma:/app/prisma
      - ./alaroko-store:/app
      - /app/node_modules
      - /app/.next

volumes:
  mysql_data:
