FROM node:alpine AS builder
WORKDIR /app
COPY . .

RUN npm install

RUN npm run prisma:generate
RUN npm run build

ENV NODE_ENV development

EXPOSE 3000

ENV PORT 3000
# HOST 0.0.0.0

CMD ["npm", "run", "dev"]
